### ISSUE TITLE
Sign up and Sign in

### ISSUE THREAD

**Issue by pbzweihander** [swsnu/swpp18-team5#13]
- [x] User Model
  - [x] Generate User model #16
  - [x] Implement authentication with Django #16 
- [x] Login View
  - [x] Generate Login component and User service #24 #28
  - [x] Implement Login Request #24
  - [x] Implement Login view #28

**Comment by pbzweihander** [comment]
All done!
